language: python
sudo: false
dist: xenial
install:
    - pip install tox
script:
    - tox

matrix:
    include:
        - env: TOXENV=py27
        - env: TOXENV=pep8
        - python: pypy
          env: TOXENV=pypy
          dist: trusty
        - python: pypy3
          env: TOXENV=pypy3
          dist: trusty
        - python: 3.5
          env: TOXENV=py35
        - python: 3.6
          env: TOXENV=py36
        - python: 3.7
          env: TOXENV=py37

notifications:
  irc: "irc.freenode.net#tiddlyweb"
